[tool.pytest.ini_options]
pythonpath = ["."]
asyncio_mode = "auto"

[project]
name = "ai-agents-orchestrator"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "pytest>=9.0.3",
]

[dependency-groups]
dev = [
    "pytest-asyncio>=1.3.0",
]
